# Generated by Django 3.1.2 on 2020-10-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201024_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=models.CharField(max_length=200, null=True), null=True),
        ),
    ]
